export const PROVINCES: string[] = [
  "Buenos Aires",
  "CABA",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const CITY_OPTIONS_BY_PROVINCE: Record<string, string[]> = {
  "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Quilmes", "Morón", "Tandil", "San Isidro", "Pilar", "Tigre", "Vicente López"],
  "CABA": ["Palermo", "Recoleta", "Belgrano", "Caballito", "Flores", "Mataderos", "Villa Urquiza", "Devoto"],
  "Córdoba": ["Córdoba", "Villa Carlos Paz", "Río Cuarto", "Alta Gracia", "Villa María"],
  "Santa Fe": ["Rosario", "Santa Fe", "Rafaela", "Venado Tuerto"],
  "Mendoza": ["Mendoza", "Godoy Cruz", "Guaymallén", "San Rafael"],
  "Tucumán": ["San Miguel de Tucumán", "Yerba Buena", "Tafí Viejo"],
  "Salta": ["Salta", "San Lorenzo", "Tartagal"],
  "Neuquén": ["Neuquén", "Plottier", "Centenario"],
  "Río Negro": ["Bariloche", "General Roca", "Cipolletti"],
  "Chubut": ["Comodoro Rivadavia", "Trelew", "Puerto Madryn"],
};
